xelatex titp.tex
bibtex chapters/1.aux
bibtex chapters/2.aux
bibtex chapters/3.aux
bibtex chapters/4.aux
bibtex chapters/5.aux
bibtex chapters/6.aux
bibtex chapters/7.aux
bibtex chapters/8.aux
bibtex chapters/9.aux
bibtex chapters/10.aux
bibtex chapters/11.aux
bibtex chapters/12.aux
bibtex chapters/13.aux
bibtex chapters/14.aux
bibtex chapters/15.aux
bibtex chapters/16.aux
bibtex chapters/17.aux
xelatex titp.tex
xelatex titp.tex